# PREDICTIVE ANALYSIS

## Import Libraries

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    classification_report, confusion_matrix,
    roc_auc_score, roc_curve)

## Load Dataset

In [3]:
df=pd.read_csv(r"Data\H1_cleaned_feature_engineering.csv")

In [4]:
df.head()

,Unnamed: 0,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,...,ReservationStatus,ReservationStatusDate,Total Guest,HasChildren,HasBabies,Total Stay Duration,Revenue,TotalPreviousBookings,CancellationRate,BookingChangeRate
0,0,0,342,2015,July,27,1,0,0,2,...,Check-Out,2015-07-01,2,0,0,0,0.0,0,0.0,0.008746
1,1,0,737,2015,July,27,1,0,0,2,...,Check-Out,2015-07-01,2,0,0,0,0.0,0,0.0,0.005420
2,2,0,7,2015,July,27,1,0,1,1,...,Check-Out,2015-07-02,1,0,0,1,75.0,0,0.0,0.000000
3,3,0,13,2015,July,27,1,0,1,1,...,Check-Out,2015-07-02,1,0,0,1,75.0,0,0.0,0.000000
4,4,0,14,2015,July,27,1,0,2,2,...,Check-Out,2015-07-03,2,0,0,2,196.0,0,0.0,0.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33967 entries, 0 to 33966
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   33967 non-null  int64
 1   IsCanceled                   33967 non-null  int64
 2   LeadTime                     33967 non-null  int64
 3   ArrivalDateYear              33967 non-null  int64
 4   ArrivalDateMonth             33967 non-null  object
 5   ArrivalDateWeekNumber        33967 non-null  int64
 6   ArrivalDateDayOfMonth        33967 non-null  int64
 7   StaysInWeekendNights         33967 non-null  int64
 8   StaysInWeekNights            33967 non-null  int64
 9   Adults                       33967 non-null  int64
 10  Children                     33967 non-null  int64
 11  Babies                       33967 non-null  int64
 12  Meal                         33967 non-null  object
 13  Country                      33967 non-null  object
 14  MarketSegment                33967 non-null  object
 15  DistributionChannel          33967 non-null  object
 16  IsRepeatedGuest              33967 non-null  int64
 17  PreviousCancellations        33967 non-null  int64
 18  PreviousBookingsNotCanceled  33967 non-null  int64
 19  ReservedRoomType             33967 non-null  object
 20  AssignedRoomType             33967 non-null  object
 21  BookingChanges               33967 non-null  int64
 22  DepositType                  33967 non-null  object
 23  DaysInWaitingList            33967 non-null  int64
 24  CustomerType                 33967 non-null  object
 25  ADR                          33967 non-null  float64
 26  RequiredCarParkingSpaces     33967 non-null  int64
 27  TotalOfSpecialRequests       33967 non-null  int64
 28  ReservationStatus            33967 non-null  object
 29  ReservationStatusDate        33967 non-null  object
 30  Total Guest                  33967 non-null  int64
 31  HasChildren                  33967 non-null  int64
 32  HasBabies                    33967 non-null  int64
 33  Total Stay Duration          33967 non-null  int64
 34  Revenue                      33967 non-null  float64
 35  TotalPreviousBookings        33967 non-null  int64
 36  CancellationRate             33967 non-null  float64
 37  BookingChangeRate            33967 non-null  float64
dtypes: float64(4), int64(23), object(11)
memory usage: 9.8+ MB

## Define Features & Target

In [6]:
target = "IsCanceled"

X = df.drop(columns=[target])
y = df[target]

In [7]:
X

,Unnamed: 0,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,ReservationStatus,ReservationStatusDate,Total Guest,HasChildren,HasBabies,Total Stay Duration,Revenue,TotalPreviousBookings,CancellationRate,BookingChangeRate
0,0,342,2015,July,27,1,0,0,2,0,...,Check-Out,2015-07-01,2,0,0,0,0.00,0,0.0,0.008746
1,1,737,2015,July,27,1,0,0,2,0,...,Check-Out,2015-07-01,2,0,0,0,0.00,0,0.0,0.005420
2,2,7,2015,July,27,1,0,1,1,0,...,Check-Out,2015-07-02,1,0,0,1,75.00,0,0.0,0.000000
3,3,13,2015,July,27,1,0,1,1,0,...,Check-Out,2015-07-02,1,0,0,1,75.00,0,0.0,0.000000
4,4,14,2015,July,27,1,0,2,2,0,...,Check-Out,2015-07-03,2,0,0,2,196.00,0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33962,40055,212,2017,August,35,31,2,8,2,1,...,Check-Out,2017-09-10,3,1,0,10,897.50,0,0.0,0.004695
33963,40056,169,2017,August,35,30,2,9,2,0,...,Check-Out,2017-09-10,2,0,0,11,2224.97,0,0.0,0.000000
33964,40057,204,2017,August,35,29,4,10,2,0,...,Check-Out,2017-09-12,2,0,0,14,2149.98,0,0.0,0.000000
33965,40058,211,2017,August,35,31,4,10,2,0,...,Check-Out,2017-09-14,2,0,0,14,1579.20,0,0.0,0.000000
33966,40059,161,2017,August,35,31,4,10,2,0,...,Check-Out,2017-09-14,2,0,0,14,1386.84,0,0.0,0.000000

In [8]:
X.shape

(33967, 37)

In [9]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33967 entries, 0 to 33966
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   33967 non-null  int64
 1   LeadTime                     33967 non-null  int64
 2   ArrivalDateYear              33967 non-null  int64
 3   ArrivalDateMonth             33967 non-null  object
 4   ArrivalDateWeekNumber        33967 non-null  int64
 5   ArrivalDateDayOfMonth        33967 non-null  int64
 6   StaysInWeekendNights         33967 non-null  int64
 7   StaysInWeekNights            33967 non-null  int64
 8   Adults                       33967 non-null  int64
 9   Children                     33967 non-null  int64
 10  Babies                       33967 non-null  int64
 11  Meal                         33967 non-null  object
 12  Country                      33967 non-null  object
 13  MarketSegment                33967 non-null  object
 14  DistributionChannel          33967 non-null  object
 15  IsRepeatedGuest              33967 non-null  int64
 16  PreviousCancellations        33967 non-null  int64
 17  PreviousBookingsNotCanceled  33967 non-null  int64
 18  ReservedRoomType             33967 non-null  object
 19  AssignedRoomType             33967 non-null  object
 20  BookingChanges               33967 non-null  int64
 21  DepositType                  33967 non-null  object
 22  DaysInWaitingList            33967 non-null  int64
 23  CustomerType                 33967 non-null  object
 24  ADR                          33967 non-null  float64
 25  RequiredCarParkingSpaces     33967 non-null  int64
 26  TotalOfSpecialRequests       33967 non-null  int64
 27  ReservationStatus            33967 non-null  object
 28  ReservationStatusDate        33967 non-null  object
 29  Total Guest                  33967 non-null  int64
 30  HasChildren                  33967 non-null  int64
 31  HasBabies                    33967 non-null  int64
 32  Total Stay Duration          33967 non-null  int64
 33  Revenue                      33967 non-null  float64
 34  TotalPreviousBookings        33967 non-null  int64
 35  CancellationRate             33967 non-null  float64
 36  BookingChangeRate            33967 non-null  float64
dtypes: float64(4), int64(22), object(11)
memory usage: 9.6+ MB

In [10]:
y

0        0
1        0
2        0
3        0
4        0
        ..
33962    0
33963    0
33964    0
33965    0
33966    0
Name: IsCanceled, Length: 33967, dtype: int64

## Encode Categorical Variables

In [11]:
X = pd.get_dummies(X, drop_first=True)

In [12]:
X

,Unnamed: 0,LeadTime,ArrivalDateYear,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,Babies,...,ReservationStatusDate_2017-09-03,ReservationStatusDate_2017-09-04,ReservationStatusDate_2017-09-05,ReservationStatusDate_2017-09-06,ReservationStatusDate_2017-09-07,ReservationStatusDate_2017-09-08,ReservationStatusDate_2017-09-09,ReservationStatusDate_2017-09-10,ReservationStatusDate_2017-09-12,ReservationStatusDate_2017-09-14
0,0,342,2015,27,1,0,0,2,0,0,...,False,False,False,False,False,False,False,False,False,False
1,1,737,2015,27,1,0,0,2,0,0,...,False,False,False,False,False,False,False,False,False,False
2,2,7,2015,27,1,0,1,1,0,0,...,False,False,False,False,False,False,False,False,False,False
3,3,13,2015,27,1,0,1,1,0,0,...,False,False,False,False,False,False,False,False,False,False
4,4,14,2015,27,1,0,2,2,0,0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33962,40055,212,2017,35,31,2,8,2,1,0,...,False,False,False,False,False,False,False,True,False,False
33963,40056,169,2017,35,30,2,9,2,0,0,...,False,False,False,False,False,False,False,True,False,False
33964,40057,204,2017,35,29,4,10,2,0,0,...,False,False,False,False,False,False,False,False,True,False
33965,40058,211,2017,35,31,4,10,2,0,0,...,False,False,False,False,False,False,False,False,False,True
33966,40059,161,2017,35,31,4,10,2,0,0,...,False,False,False,False,False,False,False,False,False,True

In [13]:
X.shape

(33967, 1112)

In [14]:
X.dtypes

Unnamed: 0                          int64
LeadTime                            int64
ArrivalDateYear                     int64
ArrivalDateWeekNumber               int64
ArrivalDateDayOfMonth               int64
                                    ...
ReservationStatusDate_2017-09-08     bool
ReservationStatusDate_2017-09-09     bool
ReservationStatusDate_2017-09-10     bool
ReservationStatusDate_2017-09-12     bool
ReservationStatusDate_2017-09-14     bool
Length: 1112, dtype: object

## Train Test Split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

## Feature Scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

In [ ]:
X_test

## Train Logistic Regression Model

In [ ]:
model = LogisticRegression()
model.fit(X_train, y_train)

## Predictions

In [ ]:
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

In [ ]:
y_pred

In [ ]:
y_prob

## Evaluation Metrics

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_prob)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("ROC-AUC:", roc_auc)

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

## ROC Curve

In [ ]:
fpr, tpr, thresholds = roc_curve(y_test, y_prob)

plt.figure()
plt.plot(fpr, tpr)
plt.plot([0, 1], [0, 1], linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Logistic Regression")
plt.show()

## Train Decision Tree

In [ ]:
dt_model = DecisionTreeClassifier(
    max_depth=5,         # control overfitting
    min_samples_split=10,
    random_state=42
)

dt_model.fit(X_train, y_train)

## Predictions

In [ ]:
y_pred_dt = dt_model.predict(X_test)
y_prob_dt = dt_model.predict_proba(X_test)[:, 1]

In [ ]:
y_pred_dt

In [ ]:
y_prob_dt

## Evaluation Metrics

In [ ]:
accuracy = accuracy_score(y_test, y_pred_dt)
precision = precision_score(y_test, y_pred_dt)
recall = recall_score(y_test, y_pred_dt)
roc_auc = roc_auc_score(y_test, y_prob_dt)

print("Decision Tree Results")
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("ROC-AUC:", roc_auc)

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))
print("\nClassification Report:\n", classification_report(y_test, y_pred_dt))

## ROC Curve

In [ ]:
fpr, tpr, _ = roc_curve(y_test, y_prob_dt)

plt.figure()
plt.plot(fpr, tpr)
plt.plot([0, 1], [0, 1], linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Decision Tree")
plt.show()