In [1]:
import numpy as np
import pandas as pd

In [52]:
tt=pd.read_csv(r"C:\Users\ACM\Desktop\H1(infotact).csv")
tt.head()

,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,ReservationStatus,ReservationStatusDate
0,0,342,2015,July,27,1,0,0,2,0,...,No Deposit,NULL,NULL,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,0,737,2015,July,27,1,0,0,2,0,...,No Deposit,NULL,NULL,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,0,7,2015,July,27,1,0,1,1,0,...,No Deposit,NULL,NULL,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,0,13,2015,July,27,1,0,1,1,0,...,No Deposit,304,NULL,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,0,14,2015,July,27,1,0,2,2,0,...,No Deposit,240,NULL,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [53]:
tt.shape

(40060, 31)

In [54]:
tt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40060 entries, 0 to 40059
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   IsCanceled                   40060 non-null  int64
 1   LeadTime                     40060 non-null  int64
 2   ArrivalDateYear              40060 non-null  int64
 3   ArrivalDateMonth             40060 non-null  object
 4   ArrivalDateWeekNumber        40060 non-null  int64
 5   ArrivalDateDayOfMonth        40060 non-null  int64
 6   StaysInWeekendNights         40060 non-null  int64
 7   StaysInWeekNights            40060 non-null  int64
 8   Adults                       40060 non-null  int64
 9   Children                     40060 non-null  int64
 10  Babies                       40060 non-null  int64
 11  Meal                         40060 non-null  object
 12  Country                      39596 non-null  object
 13  MarketSegment                40060 non-null  object
 14  DistributionChannel          40060 non-null  object
 15  IsRepeatedGuest              40060 non-null  int64
 16  PreviousCancellations        40060 non-null  int64
 17  PreviousBookingsNotCanceled  40060 non-null  int64
 18  ReservedRoomType             40060 non-null  object
 19  AssignedRoomType             40060 non-null  object
 20  BookingChanges               40060 non-null  int64
 21  DepositType                  40060 non-null  object
 22  Agent                        40060 non-null  object
 23  Company                      40060 non-null  object
 24  DaysInWaitingList            40060 non-null  int64
 25  CustomerType                 40060 non-null  object
 26  ADR                          40060 non-null  float64
 27  RequiredCarParkingSpaces     40060 non-null  int64
 28  TotalOfSpecialRequests       40060 non-null  int64
 29  ReservationStatus            40060 non-null  object
 30  ReservationStatusDate        40060 non-null  object
dtypes: float64(1), int64(17), object(13)
memory usage: 9.5+ MB

In [55]:
tt.duplicated().sum()

np.int64(6092)

In [56]:
tt.drop_duplicates(inplace=True)

In [57]:
tt.shape

(33968, 31)

In [58]:
tt.isnull().sum()

IsCanceled                       0
LeadTime                         0
ArrivalDateYear                  0
ArrivalDateMonth                 0
ArrivalDateWeekNumber            0
ArrivalDateDayOfMonth            0
StaysInWeekendNights             0
StaysInWeekNights                0
Adults                           0
Children                         0
Babies                           0
Meal                             0
Country                        446
MarketSegment                    0
DistributionChannel              0
IsRepeatedGuest                  0
PreviousCancellations            0
PreviousBookingsNotCanceled      0
ReservedRoomType                 0
AssignedRoomType                 0
BookingChanges                   0
DepositType                      0
Agent                            0
Company                          0
DaysInWaitingList                0
CustomerType                     0
ADR                              0
RequiredCarParkingSpaces         0
TotalOfSpecialRequests           0
ReservationStatus                0
ReservationStatusDate            0
dtype: int64

In [59]:
#Agent and Company contains majority null data (string), so drop
tt.drop(['Agent','Company'],axis=1,inplace=True)

In [60]:
tt.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33968 entries, 0 to 40059
Data columns (total 29 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   IsCanceled                   33968 non-null  int64
 1   LeadTime                     33968 non-null  int64
 2   ArrivalDateYear              33968 non-null  int64
 3   ArrivalDateMonth             33968 non-null  object
 4   ArrivalDateWeekNumber        33968 non-null  int64
 5   ArrivalDateDayOfMonth        33968 non-null  int64
 6   StaysInWeekendNights         33968 non-null  int64
 7   StaysInWeekNights            33968 non-null  int64
 8   Adults                       33968 non-null  int64
 9   Children                     33968 non-null  int64
 10  Babies                       33968 non-null  int64
 11  Meal                         33968 non-null  object
 12  Country                      33522 non-null  object
 13  MarketSegment                33968 non-null  object
 14  DistributionChannel          33968 non-null  object
 15  IsRepeatedGuest              33968 non-null  int64
 16  PreviousCancellations        33968 non-null  int64
 17  PreviousBookingsNotCanceled  33968 non-null  int64
 18  ReservedRoomType             33968 non-null  object
 19  AssignedRoomType             33968 non-null  object
 20  BookingChanges               33968 non-null  int64
 21  DepositType                  33968 non-null  object
 22  DaysInWaitingList            33968 non-null  int64
 23  CustomerType                 33968 non-null  object
 24  ADR                          33968 non-null  float64
 25  RequiredCarParkingSpaces     33968 non-null  int64
 26  TotalOfSpecialRequests       33968 non-null  int64
 27  ReservationStatus            33968 non-null  object
 28  ReservationStatusDate        33968 non-null  object
dtypes: float64(1), int64(17), object(11)
memory usage: 7.8+ MB

In [61]:
tt

,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,AssignedRoomType,BookingChanges,DepositType,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,ReservationStatus,ReservationStatusDate
0,0,342,2015,July,27,1,0,0,2,0,...,C,3,No Deposit,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,0,737,2015,July,27,1,0,0,2,0,...,C,4,No Deposit,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,0,7,2015,July,27,1,0,1,1,0,...,C,0,No Deposit,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,0,13,2015,July,27,1,0,1,1,0,...,A,0,No Deposit,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,0,14,2015,July,27,1,0,2,2,0,...,A,0,No Deposit,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40055,0,212,2017,August,35,31,2,8,2,1,...,A,1,No Deposit,0,Transient,89.75,0,0,Check-Out,2017-09-10
40056,0,169,2017,August,35,30,2,9,2,0,...,E,0,No Deposit,0,Transient-Party,202.27,0,1,Check-Out,2017-09-10
40057,0,204,2017,August,35,29,4,10,2,0,...,E,0,No Deposit,0,Transient,153.57,0,3,Check-Out,2017-09-12
40058,0,211,2017,August,35,31,4,10,2,0,...,D,0,No Deposit,0,Contract,112.80,0,1,Check-Out,2017-09-14
40059,0,161,2017,August,35,31,4,10,2,0,...,A,0,No Deposit,0,Transient,99.06,0,0,Check-Out,2017-09-14

In [62]:
tt['Country']=tt['Country'].fillna('Unknown')

In [63]:
tt.isnull().sum()

IsCanceled                     0
LeadTime                       0
ArrivalDateYear                0
ArrivalDateMonth               0
ArrivalDateWeekNumber          0
ArrivalDateDayOfMonth          0
StaysInWeekendNights           0
StaysInWeekNights              0
Adults                         0
Children                       0
Babies                         0
Meal                           0
Country                        0
MarketSegment                  0
DistributionChannel            0
IsRepeatedGuest                0
PreviousCancellations          0
PreviousBookingsNotCanceled    0
ReservedRoomType               0
AssignedRoomType               0
BookingChanges                 0
DepositType                    0
DaysInWaitingList              0
CustomerType                   0
ADR                            0
RequiredCarParkingSpaces       0
TotalOfSpecialRequests         0
ReservationStatus              0
ReservationStatusDate          0
dtype: int64

In [64]:
tt.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33968 entries, 0 to 40059
Data columns (total 29 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   IsCanceled                   33968 non-null  int64
 1   LeadTime                     33968 non-null  int64
 2   ArrivalDateYear              33968 non-null  int64
 3   ArrivalDateMonth             33968 non-null  object
 4   ArrivalDateWeekNumber        33968 non-null  int64
 5   ArrivalDateDayOfMonth        33968 non-null  int64
 6   StaysInWeekendNights         33968 non-null  int64
 7   StaysInWeekNights            33968 non-null  int64
 8   Adults                       33968 non-null  int64
 9   Children                     33968 non-null  int64
 10  Babies                       33968 non-null  int64
 11  Meal                         33968 non-null  object
 12  Country                      33968 non-null  object
 13  MarketSegment                33968 non-null  object
 14  DistributionChannel          33968 non-null  object
 15  IsRepeatedGuest              33968 non-null  int64
 16  PreviousCancellations        33968 non-null  int64
 17  PreviousBookingsNotCanceled  33968 non-null  int64
 18  ReservedRoomType             33968 non-null  object
 19  AssignedRoomType             33968 non-null  object
 20  BookingChanges               33968 non-null  int64
 21  DepositType                  33968 non-null  object
 22  DaysInWaitingList            33968 non-null  int64
 23  CustomerType                 33968 non-null  object
 24  ADR                          33968 non-null  float64
 25  RequiredCarParkingSpaces     33968 non-null  int64
 26  TotalOfSpecialRequests       33968 non-null  int64
 27  ReservationStatus            33968 non-null  object
 28  ReservationStatusDate        33968 non-null  object
dtypes: float64(1), int64(17), object(11)
memory usage: 7.8+ MB

In [66]:
tt.to_csv(r"C:\Users\ACM\Desktop\H1_cleaned.csv")